apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jj-gym-postgres-allow-api-only
  namespace: jj-gym
spec:
  podSelector:
    matchLabels:
      app: jj-gym-postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: jj-gym-api
      ports:
        - protocol: TCP
          port: 5432

